let shopItemsData = [
    {
      id: 1,
      name: "Casual Shirt",
      img: "images/img-1.jpg",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      price: 45,
    },
    {
      id: 2,
      name: "Office Shirt",
      img: "images/img-2.jpg",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      price: 100,
    },
    {
      id: 3,
      name: "T Shirt",
      img: "images/img-3.jpg",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      price: 25,
    },
    {
      id: 4,
      name: "Mens Suit",
      img: "images/img-4.jpg",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      price: 300,
    },
    {
      id: 5,
      name: "Mens Tie",
      img: "images/img-5.png",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      price: 25,
    },
    {
      id: 6,
      name: "Casual shoes",
      img: "images/img-6.png",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      price: 200,
    },
    {
      id: 7,
      name: "black suit",
      img: "images/img-7.png",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      price: 450,
    },
    {
      id: 8,
      name: "polo shirt",
      img: "images/img-8.png",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      price: 45,
    },
    {
      name: "denim shirt",
      id: 9,
      img: "images/img-9.png",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      price: 85,
    },
    {
      id: 10,
      name: "denim pants",
      img: "images/img-10.png",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      price: 120,
    },
    {
      id: 11,
      name: "basic cap",
      img: "images/img-11.png",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      price: 35,
    },
    {
      id: 12,
      name: "leather boots",
      img: "images/img-12.png",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      price: 350,
    },
  ];